# Generated by Django 5.1 on 2025-11-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI'), ('system', 'System')], default='user', max_length=20)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('model_path', models.CharField(default='./qwen2.5b_q4k.gguf', max_length=120)),
                ('top_p', models.FloatField(default=1.0)),
                ('top_k', models.IntegerField(default=50)),
            ],
        ),
    ]
