# Generated by Django 5.1 on 2025-11-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textgen', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='textgenerationsettings',
            name='identifier',
            field=models.CharField(default='default', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='textgenerationsettings',
            name='seed',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='textgenerationsettings',
            name='max_tokens',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='textgenerationsettings',
            name='model_path',
            field=models.CharField(default='./qwen2.5b.gguf', max_length=200),
        ),
        migrations.AlterField(
            model_name='textgenerationsettings',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
